# -*- coding: utf-8 -*-
"""פתרון תרגיל מסכם - קבוצה 4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZCQYPuvw6yCoegj6VmftnbAcUrpfaziu
"""

import pandas as pd


#import csv files
url_csv = {
   "candies_factories": "https://drive.google.com/uc?export=download&id=1KgboJ9kQ90uTUjLEo7yFqdj23agK0NVa",
   "candy_products": "https://drive.google.com/uc?export=download&id=1IxRIPCJFj1cufkjQw2K3K-D07B6lkauR",
   "customers": "https://drive.google.com/uc?export=download&id=1sw3x4c6ki20eMuf7mGVLJRSn63G6lCDT",
   "sales_ca": "https://drive.google.com/uc?export=download&id=18SYEbr8X21DmYXQAi2eMU3O-u0e6e-Mc",
   "sales_us": "https://drive.google.com/uc?export=download&id=1c_b5frSJjmV1gBJN-9LfhZtXyKeHfHQ2",
}


candy_factory = pd.read_csv(url_csv['candies_factories'])
candy_products = pd.read_csv(url_csv['candy_products'])
sales_ca = pd.read_csv(url_csv['sales_ca'])
sales_us = pd.read_csv(url_csv['sales_us'])
customers = pd.read_csv(url_csv['customers'])

#import json file
url = "https://drive.google.com/uc?export=download&id=1wvw--W5gwcYc3E3h2oTdGXi8uMS0qRoZ"
candy_targets = pd.read_json(url)

candy_factory.head(5)
candy_products.head(5)
candy_targets.head(5)
customers.head(5)
sales_ca.head(5)
sales_us.head(5)

candy_factory.tail(5)
candy_products.tail(5)
candy_targets.tail(5)
customers.tail(5)
sales_ca.tail(5)
sales_us.tail(5)

# שלב 2: חקירת הנתונים

f"{candy_factory.shape[0]} rows, {candy_factory.shape[1]} columns"
f"{candy_products.shape[0]} rows, {candy_products.shape[1]} columns"
f"{candy_targets.shape[0]} rows, {candy_products.shape[1]} columns"
f"{customers.shape[0]} rows, {customers.shape[1]} columns"
f"{sales_ca.shape[0]} rows, {customers.shape[1]} columns"
f"{sales_us.shape[0]} rows, {customers.shape[1]} columns"

candy_factory.info()
candy_products.info()
candy_targets.info()
customers.info()
sales_ca.info()
sales_us.info()

candy_factory.describe()
candy_products.describe()
candy_targets.describe()
customers.describe()
sales_ca.describe()
sales_us.describe()

# 3.1 שלב 3: ניקוי שמות עמודות

clean_column_name = lambda x: x.strip().lower().replace(' ', '_')

candy_factory.columns = candy_factory.columns.to_series().apply(clean_column_name)

candy_products.columns = candy_products.columns.to_series().apply(clean_column_name)

candy_targets.columns = candy_targets.columns.to_series().apply(clean_column_name)

customers.columns = customers.columns.to_series().apply(clean_column_name)

sales_ca.columns = sales_ca.columns.to_series().apply(clean_column_name)

sales_us.columns = sales_us.columns.to_series().apply(clean_column_name)

# 3.2 שלב 3: ניקוי שמות עמודות
ship_cost = {
      'First Class' : 10,
      'Second Class' : 5,
      'Standard Class' : 3,
      'Same Day' : 20
  }
  sales_all = pd.concat([sales_ca, sales_us], ignore_index=True)
  sales_all['shipping_cost'] = sales_all['ship_mode'].map(ship_cost)
  sales_all

# 3.3  שימוש ב־ apply ליצירת עמודות חדשות
sales_all['units'] = pd.to_numeric(sales_all['units'], errors='coerce')
sales_all['price_per_unit'] = pd.to_numeric(sales_all['price_per_unit'], errors='coerce')
sales_all['Level'] = sales_all.apply(
    lambda x: 'Low' if (x['price_per_unit'] * x['units']) <= 50
               else ('Medium' if 50 < (x['price_per_unit'] * x['units']) <= 200
               else 'High'),
    axis=1
)
sales_all

#--3.4
sales_all['total_price'] = sales_all['price_per_unit'] * sales_all['units']
sales_all

#--3.5
sales_all['order_date'] = pd.to_datetime(sales_all['order_date'])
sales_all['year'] = sales_all['order_date'].dt.year
sales_all

#---3.6
sales_all['total_price_after_discount'] = sales_all.apply(
    lambda x: x['total_price'] * 0.9 if x['units'] > 5 else x['total_price'],
    axis=1
)
sales_all

#----3.7
customers['address'] = customers['address'].astype('string')
customers['address'] = customers['address'].replace('nan', 'Unkown_adress')
customers

#-----3.8
sales_ca['order_date'] = pd.to_datetime(sales_ca['order_date'])
sales_us['order_date'] = pd.to_datetime(sales_us['order_date'])
sales_ca['ship_date'] = pd.to_datetime(sales_ca['ship_date'])
sales_us['ship_date'] = pd.to_datetime(sales_us['ship_date'])

#----3.9

candy_factory.info()
candy_products.info()
candy_targets.info()
customers.info()
sales_ca.info()
sales_us.info()

#----4
sales = pd.concat([sales_ca, sales_us], ignore_index=True)
customers_sales = pd.merge(customers, sales, on = 'customer_id')
customers_sales = customers_sales.rename(columns={'age': 'customer_age'})
customers_sales['city'] = customers_sales['address'].str.split(',', expand=True)[1]
customers_sales['address'] = customers_sales['address'].str.split(',', expand=True)[0]
customers_sales = customers_sales.rename(columns={'address':'customer_address'})
customers_sales['customer_id']
customers_sales.info()

#---4.1
print(sales_all.loc[:, ['customer_id', 'product_name', 'units', 'total_price']])
print(sales_all.iloc[:5,1:5])

print(sales_all[(sales_all['units'] > 3) | (sales_all['total_price'] > 20)],['product_name','total_price'])

#----4.3
division_sales = sales.groupby('division')['sales'].sum().reset_index()
comparison_division = division_sales.merge(candy_targets, on='division')
comparison_division['target_reached'] = comparison_division['sales'] >= comparison_division['target']
comparison_division

#----שלב 5
combined_data = sales_all.merge(candy_products, on=['product_id', 'division', 'product_name'], how='left') \
.merge(candy_factory) \
.merge(candy_targets) \
.merge(customers)

#---שלב 6
top_sales = combined_data.sort_values(by='sales', ascending=False).head(1)
top_sales[['product_name', 'sales']]

combined_data['num_orders'] = combined_data.groupby('state/province')['order_id'].transform('count')
combined_data.loc[:, ['state/province','city','num_orders']]

combined_data['month_name'] = combined_data['order_date'].dt.month_name()
sales_avg = combined_data.groupby('month_name')['sales'].mean()
sales_avg

top_customer_sales = combined_data.loc[:, ['customer_id','sales']]
top_customer_sales.sort_values('sales', ascending=False).head(5)

weakest_prod = combined_data.loc[:, ['product_name','sales']]
weakest_prod.sort_values('sales', ascending=True).head(5)

avg_customer_sale = sales_us.groupby('customer_id')['sales'].mean()
avg_customer_sale

combined_data['total_price'] = pd.to_numeric(combined_data['total_price'], errors='coerce').fillna(0)
sum_total_price = combined_data.groupby('order_id')['total_price'].agg(['sum','min','max','mean'])
sum_total_price

cities_df = combined_data.loc[:,['country/region','city','state/province','postal_code','region']]
cities_df

cities_df.to_csv('cities.csv', index=False)